language: node_js
install:
  - npm install
  - npm install -g codecov

node_js:
  - "8"
  - "10"
  - "12"

script:
  - npm run coverage

after_script:
  - if [[ `node --version` == *10* ]]; then codecov; fi